name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  analyze-scripts:
    name: Check Shell Scripts
    runs-on: macos-latest
    env:
      JOB_TYPE: ANALYZE
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          brew install shellcheck
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Run shellcheck
        run: find . \( -name "*.tool" -o -name "*.command" -o -name "*.sh" \) -exec sh -c 'for TargetFile; do shellcheck --severity=info "${TargetFile}" || exit 1; done' sh {} +
